repos:
  - repo: local
    hooks:
      # Black for formatting
      - id: black
        verbose: true
        name: black
        entry: black
        language: system
        types: [python]

      # Flake8 for linting
      - id: flake8
        verbose: true
        name: flake8
        entry: flake8
        language: system
        types: [python]

      # Pytest for running tests
      - id: pytest
        verbose: true
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
        args: [-v, --cov=src]

      # Pyright for type checking
      - id: pyright
        verbose: true
        name: pyright
        entry: pyright
        language: node
        types: [python]
